# Generated by Django 5.2.16 on 2026-07-16 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_attendance_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='upload_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed')], default='pending', max_length=50, null=True, verbose_name='Upload Status'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Uploaded at'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_url',
            field=models.URLField(blank=True, null=True, verbose_name='YouTube URL'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='YouTube Video ID'),
        ),
    ]
