# Generated by Django 5.2.16 on 2026-07-16 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_lesson_upload_status_lesson_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='failure_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Failure reason'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='local_file_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Local file path'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='upload_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('failed', 'Failed'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='pending', max_length=50, null=True, verbose_name='Upload Status'),
        ),
    ]
