# Generated by Django 5.2.16 on 2026-07-18 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lesson_failure_reason_lesson_local_file_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('present', 'Present (Keldi)'), ('late', 'Late (Kechikdi)'), ('absent', 'Absent (Kelmadi)')], default='present', max_length=20, verbose_name='Status'),
        ),
    ]
