# Generated by Django 5.2.16 on 2026-07-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='telegram_file_id',
        ),
        migrations.AddField(
            model_name='material',
            name='file',
            field=models.FileField(blank=True, help_text='PDF fayllar uchun', null=True, upload_to='materials/', verbose_name='File (PDF)'),
        ),
        migrations.AddField(
            model_name='material',
            name='link',
            field=models.URLField(blank=True, help_text='Audio uchun YouTube ssilkasi', max_length=500, null=True, verbose_name='YouTube/Audio Link'),
        ),
        migrations.AlterField(
            model_name='material',
            name='type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('audio', 'Audio')], default='pdf', max_length=10, verbose_name='Type'),
        ),
    ]
