# Generated by Django 5.2.16 on 2026-07-18 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_remove_material_telegram_file_id_material_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='type',
        ),
    ]
