# Generated by Django 5.2.16 on 2026-08-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0007_remove_material_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('grammar', 'Grammatika'), ('vocabulary', "Lug'at"), ('speaking', "So'zlashuv"), ('writing', 'Yozish')], default='grammar', max_length=20, verbose_name='Toifa'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('a1', "Boshlang'ich (A1)"), ('a2', 'Elementar (A2)'), ('b1', "O'rta (B1)"), ('b2', "Yuqori O'rta (B2)"), ('c1', "Ilg'or (C1)")], default='a1', max_length=20, verbose_name='Daraja'),
        ),
        migrations.AddField(
            model_name='course',
            name='status',
            field=models.CharField(choices=[('active', 'Faol'), ('draft', 'Qoralama')], default='active', max_length=20, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='course',
            name='monthly_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monthly price'),
        ),
    ]
