# Generated by Django 5.2.16 on 2026-08-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0008_course_category_course_level_course_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': "Yo'qlama", 'verbose_name_plural': "Yo'qlamalar"},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['-created_at'], 'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AlterModelOptions(
            name='enrollment',
            options={'verbose_name': 'Guruhga qabul', 'verbose_name_plural': 'Guruhga qabullar'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['-created_at'], 'verbose_name': 'Guruh', 'verbose_name_plural': 'Guruhlar'},
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-date'], 'verbose_name': 'Dars', 'verbose_name_plural': 'Darslar'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': "O'quv materiali", 'verbose_name_plural': "O'quv materiallari"},
        ),
    ]
