# Generated by Django 5.2.16 on 2026-08-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_parents'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchi', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
    ]
