# Generated by Django 5.2.16 on 2026-07-16 12:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0003_lesson_upload_status_lesson_uploaded_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha/Mavzu')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif/Savollar')),
                ('task_type', models.CharField(choices=[('homework', 'Uy vazifasi'), ('quiz', 'Kichik test'), ('exam', 'Imtihon')], default='homework', max_length=20, verbose_name='Topshiriq turi')),
                ('max_score', models.IntegerField(default=100, verbose_name='Maksimal ball')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Topshirish muddati')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='lessons.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': 'Topshiriq/Imtihon',
                'verbose_name_plural': 'Topshiriqlar va Imtihonlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Olingan ball')),
                ('teacher_feedback', models.TextField(blank=True, null=True, verbose_name="O'qituvchi fikri")),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='grades', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tasks.task', verbose_name='Topshiriq/Imtihon')),
            ],
            options={
                'verbose_name': 'Baho/Ball',
                'verbose_name_plural': 'Baholar va Ballar',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'student')},
            },
        ),
    ]
