# Generated by Django 5.2.16 on 2026-07-16 13:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='skill_type',
            field=models.CharField(choices=[('reading', "Reading (O'qish)"), ('writing', 'Writing (Yozish)'), ('listening', 'Listening (Eshitish)'), ('speaking', 'Speaking (Gapirish)'), ('grammar', 'Grammar (Grammatika)')], default='grammar', max_length=20, verbose_name="Ko'nikma turi"),
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text_response', models.TextField(blank=True, null=True, verbose_name='Yozma javob')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='submissions/', verbose_name='Ilova fayli (Rasm, PDF yoki Audio)')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('graded', 'Baholandi')], default='pending', max_length=20, verbose_name='Holati')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='tasks.task', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Topshiriq javobi',
                'verbose_name_plural': 'Topshiriq javoblari',
                'ordering': ['-created_at'],
                'unique_together': {('task', 'student')},
            },
        ),
    ]
