# Generated by Django 5.2.16 on 2026-07-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task_skill_type_submission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Kod')),
                ('name', models.CharField(max_length=100, verbose_name='Nomi')),
                ('description', models.CharField(max_length=255, verbose_name='Tavsif')),
                ('icon', models.CharField(default='🏆', max_length=50, verbose_name='Ikonka (Emoji)')),
            ],
            options={
                'verbose_name': 'Nishon/Yutuq',
                'verbose_name_plural': 'Nishonlar va Yutuqlar',
            },
        ),
        migrations.AddField(
            model_name='grade',
            name='audio_feedback',
            field=models.FileField(blank=True, null=True, upload_to='grades/audio/', verbose_name='Ovozli izoh (Audio feedback)'),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_late',
            field=models.BooleanField(default=False, verbose_name='Kechikib topshirildimi'),
        ),
        migrations.AddField(
            model_name='submission',
            name='selected_answers',
            field=models.JSONField(blank=True, default=dict, help_text="Format: {'question_id': 'A'}", verbose_name='Belgilangan test javoblari'),
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('question_text', models.TextField(verbose_name='Savol matni')),
                ('option_a', models.CharField(max_length=255, verbose_name='A variant')),
                ('option_b', models.CharField(max_length=255, verbose_name='B variant')),
                ('option_c', models.CharField(max_length=255, verbose_name='C variant')),
                ('option_d', models.CharField(max_length=255, verbose_name='D variant')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=2, verbose_name="To'g'ri javob")),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='tasks.task', verbose_name='Topshiriq')),
            ],
            options={
                'verbose_name': 'Test savoli',
                'verbose_name_plural': 'Test savollari',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('awarded_at', models.DateTimeField(auto_now_add=True, verbose_name='Berilgan vaqt')),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awarded_to', to='tasks.badge', verbose_name='Nishon')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earned_badges', to=settings.AUTH_USER_MODEL, verbose_name="O'quvchi")),
            ],
            options={
                'verbose_name': "O'quvchi nishoni",
                'verbose_name_plural': "O'quvchilar nishonlari",
                'unique_together': {('student', 'badge')},
            },
        ),
    ]
