# Generated by Django 5.2.16 on 2026-08-17 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0009_alter_attendance_options_alter_course_options_and_more'),
        ('tasks', '0003_badge_grade_audio_feedback_submission_is_late_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VocabularySet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255, verbose_name='Mavzu nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vocabulary_sets', to='lessons.group', verbose_name='Guruh')),
            ],
            options={
                'verbose_name': "Lug'at to'plami",
                'verbose_name_plural': "Lug'at to'plamlari",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VocabularyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('word', models.CharField(max_length=255, verbose_name="Inglizcha so'z")),
                ('translation', models.CharField(max_length=255, verbose_name='Tarjimasi / Sinonimi')),
                ('vocab_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='tasks.vocabularyset', verbose_name="Lug'at to'plami")),
            ],
            options={
                'verbose_name': "So'z juftligi",
                'verbose_name_plural': "So'z juftliklari",
                'ordering': ['created_at'],
            },
        ),
    ]
