# Generated by Django 5.2.16 on 2026-08-17 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='domain',
            options={'verbose_name': 'Domen', 'verbose_name_plural': 'Domenlar'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Markaz', 'verbose_name_plural': 'Markazlar'},
        ),
    ]
